# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-22 12:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_useraccount_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.URLField(default='/static/src/img/avatar.png', null=True)),
                ('description', models.TextField(null=True)),
                ('prone_number', models.CharField(max_length=14, null=True)),
                ('position', models.CharField(choices=[('AS', 'Assistant'), ('EN', 'Engineer'), ('DC', 'Docent'), ('PS', 'Professor'), ('LA', 'laboratorian worker'), ('AD', 'Administrator'), ('SC', 'Secretary'), ('AC', 'Accountant'), ('PR', 'Pro-rector'), ('DP', 'Head of Department'), ('RC', 'Rector'), ('DR', 'Director')], max_length=40)),
            ],
        ),
    ]
