# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-09 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20180509_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_of_action',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='finishes_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='starts_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
